# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sur_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sur_name', models.CharField(max_length=100)),
                ('years_old', models.IntegerField()),
                ('oput', models.IntegerField()),
                ('his_photo', models.ImageField(height_field=100, upload_to=b'', width_field=100)),
            ],
        ),
        migrations.CreateModel(
            name='MastersWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(height_field=100, upload_to=b'', width_field=100)),
                ('photo_2', models.ImageField(height_field=100, upload_to=b'', width_field=100)),
                ('photo_3', models.ImageField(height_field=100, upload_to=b'', width_field=100)),
                ('photo_4', models.ImageField(height_field=100, upload_to=b'', width_field=100)),
                ('photo_5', models.ImageField(height_field=100, upload_to=b'', width_field=100)),
            ],
        ),
    ]
