# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_mastersworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='his_photo',
        ),
    ]
