# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_master_his_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
