# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161017_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
