# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='his_photo',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
