# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_master'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Master',
        ),
    ]
