# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20161018_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text_of_comment', models.TextField()),
                ('comments_pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='count_of_records',
            new_name='topic_count_of_records',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='header_text',
            new_name='topic_header_text',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='pub_date',
            new_name='topic_pub_date',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Topic'),
        ),
    ]
